### ISSUE TITLE
Starting in Android Gradle Plugin 2.2.0 no longer has unaligned apks

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-unaligned-apks-remover-plugin#7]
I found this out here: https://github.com/square/spoon/issues/389

Google Issues: https://code.google.com/p/android/issues/detail?id=212591 and https://code.google.com/p/android/issues/detail?id=212591#c15

**Comment by vanniktech** [comment]
Oh cool then I guess I can mark this one as deprecated.

**Comment by jaredsburrows** [comment]
@vanniktech Yeah. You probably do not see the "Deleting unaligned apk" message anymore because they are already deleted.

**Comment by vanniktech** [comment]
Thank you. I deprecated it.
